# Generated by Django 3.1.2 on 2021-01-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an option (e.g. active / not active)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a language (e.g. de/de)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tag (e.g. tutoring)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('i', 'in Work'), ('n', 'new'), ('a', 'Available'), ('f', 'false')], default='i', help_text='word status', max_length=1)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.active')),
                ('language', models.ManyToManyField(blank=True, default='deutsch', help_text='Select a language for the word', to='catalog.Language')),
                ('tag', models.ManyToManyField(help_text='Select a tag for this word', to='catalog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='IPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(max_length=400)),
                ('syllable', models.IntegerField()),
                ('stress', models.CharField(max_length=40)),
                ('sampa', models.CharField(max_length=400)),
                ('audio', models.FileField(default='catalog/Audio/AudioMissing.mp3', upload_to='catalog/Audio/')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.active')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.word')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
