# Generated by Django 3.1.2 on 2020-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='default_ipa',
        ),
        migrations.AddField(
            model_name='word',
            name='default_ipa',
            field=models.ManyToManyField(null=True, to='catalog.ipa'),
        ),
    ]
