# Generated by Django 3.0.8 on 2020-07-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200704_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ipa',
        ),
    ]
