# Generated by Django 3.1.2 on 2021-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_word_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
