# Generated by Django 3.0.8 on 2020-07-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_ipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(max_length=400)),
                ('syllable', models.IntegerField(max_length=2)),
                ('stress', models.CharField(max_length=20)),
                ('sampa', models.CharField(max_length=400)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.active')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Word')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
