# Generated by Django 3.0.8 on 2020-07-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200705_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipa',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.word'),
        ),
    ]
