# Generated by Django 2.1.7 on 2020-11-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201028_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipa',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.word'),
        ),
    ]
