# Generated by Django 2.1.7 on 2020-11-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20201103_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipa',
            name='audio',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='ipa',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag for this word', to='catalog.tag'),
        ),
    ]
