# Generated by Django 3.1.2 on 2020-11-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20201110_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipa',
            name='audio',
            field=models.FileField(default='catalog/Audio/AudioMissing.mp3', upload_to='catalog/Audio/'),
        ),
    ]
