# Generated by Django 3.1.2 on 2020-11-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201110_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipa',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='ipa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ipa'),
        ),
    ]
