# Generated by Django 3.1.2 on 2020-11-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20201116_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='ipa',
            new_name='ipaID',
        ),
        migrations.AddField(
            model_name='ipa',
            name='wordID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.word'),
        ),
    ]
