# Generated by Django 3.1.2 on 2020-11-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20201123_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='ipaID',
            new_name='ipas',
        ),
    ]
