# Generated by Django 3.1.2 on 2020-11-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20201123_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipa',
            old_name='wordID',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='ipas',
        ),
    ]
